version: '3'

services:
  app:
    build: messenger_project
    ports:
      - "8000:8000"
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"

volumes:
  db_data:
